# Generated by Django 3.0.7 on 2022-01-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='categary',
            name='photo',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
