# Generated by Django 3.0.7 on 2022-01-15 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_register_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
